# Generated by Django 5.1.4 on 2025-02-20 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
